config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'internet_orders#index'

  resources :internet_orders 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/internet_order.rb
class InternetOrder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/internet_orders_controller.rb
class InternetOrdersController < ApplicationController
  before_action :set_internet_order, only: [:show, :edit, :update, :destroy]

  # GET /internet_orders
  # GET /internet_orders.json
  def index
    @internet_orders  =  InternetOrder.order("created_at desc").page(params[:page]).per(params[:limit] || 10)
    @internet_orders.where!('name like ?', "%#{params[:name]}%") if params[:name].present?
    @internet_orders.where!('phone_number like ?', "%#{params[:phone_number]}%") if params[:phone_number].present?
    #@internet_orders.where!(name: params[:name]) if params[:name].present?
    #@internet_orders.where!(phone_number: params[:phone_number]) if params[:phone_number].present?
    respond_to do |format|
       format.xlsx # {
      #   response.headers['Content-Disposition'] = "attachment; filename= Internet_Order.xlsx "
      # }
      format.html { render :index }
    end
  end

  # GET /internet_orders/1
  # GET /internet_orders/1.json
  def show
  end

  # GET /internet_orders/new
  def new
    @internet_order = InternetOrder.new
  end

  # GET /internet_orders/1/edit
  def edit
  end

  # POST /internet_orders
  # POST /internet_orders.json
  def create
    @internet_order = InternetOrder.new(internet_order_params)

    respond_to do |format|
      if @internet_order.save
        format.html { redirect_to internet_orders_url, notice: 'Internet order was successfully created.' }
        format.json { render :index, status: :created, location: @internet_order }
      else
        format.html { render :new }
        format.json { render json: @internet_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /internet_orders/1
  # PATCH/PUT /internet_orders/1.json
  def update
    respond_to do |format|
      if @internet_order.update(internet_order_params)
        format.html { redirect_to internet_orders_url, notice: 'Internet order was successfully updated.' }
        format.json { render :show, status: :ok, location: @internet_order }
      else
        format.html { render :edit }
        format.json { render json: @internet_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internet_orders/1
  # DELETE /internet_orders/1.json
  def destroy
    @internet_order.destroy
    respond_to do |format|
      format.html { redirect_to internet_orders_url, notice: 'Internet order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_internet_order
      @internet_order = InternetOrder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def internet_order_params
      params.require(:internet_order).permit(:sn, :apply_date, :name, :fb_id, :phone_number, :postal_code, :dob, :house_type, :kouji_date, :plan, :link, :conclusion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/internet_orders_helper.rb
module InternetOrdersHelper
end

app/views/internet_orders/_form.html.erb
<%= form_with(model: internet_order, local: true) do |form| %>
  <% if internet_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(internet_order.errors.count, "error") %> prohibited this internet_order from being saved:</h2>

      <ul>
        <% internet_order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :sn %>
    <%#= form.number_field :sn %>
  </div>

  <div class="field">
    <%= form.label :apply_date %>
    <%= form.date_select :apply_date %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :fb_id %>
    <%= form.text_field :fb_id %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.number_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :DOB %>
    <%= form.date_select :dob %>
  </div>

  <div class="field">
    <%= form.label :house_type %>
    <%= form.select :house_type, options_for_select([ ['', ], 
                                                      ['Mansion', 'Mansion'], 
                                                      ['Apartment', 'Apartment']]) %>
    
  </div>

  <div class="field">
    <%= form.label :kouji_date %>
    <%= form.date_select :kouji_date %>
  </div>

  <div class="field">
    <%= form.label :plan %>
    <%= form.text_field :plan %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :conclusion %>
    <%= form.text_area :conclusion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/internet_orders/_search.html.erb
<div id="myDIV" style="display:none">
    <%= form_tag({}, {:method => 'get',:class => 'form-control-sm'}) do %>
        <%=label_tag "Name:" %>
        <%= text_field_tag :name, params[:name],  autocomplete: 'off' %> &nbsp;    
        <%=label_tag "Phone Num.:" %>
        <%= text_field_tag :phone_number, params[:phone_number] , autocomplete: 'off' %>
        <div class="select-tag">
        Show <%= select_tag :limit, options_for_select([5, 10, 15, 20], selected: params[:limit] || 10), onchange: "$('#limit_form').submit();" %> documents per page
        </div>
        <%= submit_tag 'search', :disable_with => 'Searching...' %>
        <%= link_to 'clear', :action => 'index'%>
  <% end %>
</div>

app/views/internet_orders/edit.html.erb
<h1>Editing Internet Order</h1>

<%= render 'form', internet_order: @internet_order %>

<%= link_to 'Show', @internet_order %> |
<%= link_to 'Back', internet_orders_path %>

app/views/internet_orders/index.html.erb
<script> 
 function myFunction() {
  var x = document.getElementById('myDIV');
  if (x.style.display === 'none') {
      x.style.display = 'block';
  } else {
      x.style.display = 'none';
    }
  }
 </script>

<h1>Internet Orders</h1>
<p id="notice"><%= notice %></p>
<%= link_to 'New Internet Order', new_internet_order_path %>

<button class="s-btn popup" style="margin-left:0px;"  onclick="myFunction()">
  Serarch <i class="fas fa-chevron-down"></i>
</button>




<%= render :partial => 'search' %>

<%= link_to 'Download as Excel', url_for(request.parameters.merge(format: :xlsx))%>

<table class ="table table-sm table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Sn</th>
      <th>Apply date</th>
      <th>Name</th>
      <th>Facebook link</th>
      <th>Phone number</th>
      <th>Postal code</th>
      <th>DOB</th>
      <th>House type</th>
      <th>Kouji date</th>
      <th>Plan</th>
      <th>Link</th>
      <th>Conclusion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @internet_orders.each do |internet_order| %>
      <tr>
        <td><%= internet_order.sn %></td>
        <td><%= internet_order.apply_date.strftime('%Y-%m-%d') %></td>
        <td><%= internet_order.name %></td>
        <td><%= internet_order.fb_id %></td>
        <td><%= internet_order.phone_number %></td>
        <td><%= internet_order.postal_code %></td>
        <td><%= internet_order.dob.strftime('%Y-%m-%d') %></td>
        <td><%= internet_order.house_type %></td>
        <td><%= internet_order.kouji_date.strftime('%Y-%m-%d') %></td>
        <td><%= internet_order.plan %></td>
        <td><%= internet_order.link %></td>
        <td><%= internet_order.conclusion %></td>
        <td><%= link_to 'Show', internet_order %></td>
        <td><%= link_to 'Edit', edit_internet_order_path(internet_order) %></td>
        <td><%= link_to 'Destroy', internet_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="item-space-around">
  <%= paginate @internet_orders %>
</div>

app/views/internet_orders/new.html.erb
<h1>New Internet Order</h1>

<%= render 'form', internet_order: @internet_order %>

<%= link_to 'Back', internet_orders_path %>

app/views/internet_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sn:</strong>
  <%= @internet_order.sn %>
</p>

<p>
  <strong>Apply date:</strong>
  <%= @internet_order.apply_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @internet_order.name %>
</p>

<p>
  <strong>Fb:</strong>
  <%= @internet_order.fb_id %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @internet_order.phone_number %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @internet_order.postal_code %>
</p>

<p>
  <strong>DOB:</strong>
  <%= @internet_order.dob %>
</p>

<p>
  <strong>House type:</strong>
  <%= @internet_order.house_type %>
</p>

<p>
  <strong>Kouji date:</strong>
  <%= @internet_order.kouji_date %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @internet_order.plan %>
</p>

<p>
  <strong>Link:</strong>
  <%= @internet_order.link %>
</p>

<p>
  <strong>Conclusion:</strong>
  <%= @internet_order.conclusion %>
</p>

<%= link_to 'Edit', edit_internet_order_path(@internet_order) %> |
<%= link_to 'Back', internet_orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  crossorigin="anonymous">


    <title>Internet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous"></script>
    
  </head>

  <body>
    <%= yield %>

   
  </body>
</html>